### ISSUE TITLE
Alaska results by county?

### ISSUE THREAD

**Issue by ijconlon** [favstats/USElection2020-NYT-Results#4]
Thanks for putting this together! One issue I've come across is that the Alaska results in the dataset are for electoral districts (EDs) rather than counties. Is it possible to get county-level data for Alaska? I believe all other states are reported by county, so the problem is limited to Alaska.

**Comment by favstats** [comment]
Yes, it's something I noticed as well. Unfortunately, this is simply how the New York Times provides the data so there is little that I can do.

Depending on what you want to do though, there might be sort of a hacky fix for this: you can just calculate the average of the metrics across all electoral districts in Alaska and then treat the whole of Alaska as one unit. That's what I did for the graph you see in the `README`.

**Comment by ijconlon** [comment]
Ah, good idea--and that works! Doesn't look like county results are available elsewhere either. Weird.
